name: Sync fork

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
    
jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Fork Sync
        # You may pin to the exact commit or the version.
        # uses: tgymnich/fork-sync@0cc6ac48fd51415e7c34e5b8823021bc952a5f5f
        uses: tgymnich/fork-sync@v1.2.1
        with:
          # Owner of the forked repository
          owner: chrisvoo
          # Token for the github API
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Branch to track
          head: master
          # Branch to keep updated
          base: master
          # Merge method to use
          merge_method: merge
          # The title of the pull request
          pr_title: Fork Sync
          # The message in the pull request
          pr_message: Mergin Koel
          # ignore Exceptions
          ignore_fail: false
